name: download-docker-image
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pull
        run: docker pull alpine/openclaw:latest
      - name: save
        run: docker save alpine/openclaw:latest > openclaw.tar
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: openclaw-package
          path: openclaw.tar
          retention-days: 1
